version: '3.6'

services:
  keycloakdb:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  foodydb:
    image: postgres:16
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: foodybackenddb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "54321:5432"


  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:23.0.7
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloakdb/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}

      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false

      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true

      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
#    volumes:
#      - keycloak:/opt/keycloak/data/
    restart: always
    ports:
      - "9090:8080"
    command:
      - "start-dev"
    depends_on:
      - keycloakdb
#    networks:
#      - keycloak_network


volumes:
  postgres_data:
    driver: local
  db:
    driver: local

#networks:
#  keycloak_network:
#    driver: bridge